[features]
seeds = false
skip-lint = false
[programs.localnet]
gdmultisig = "2omcykYnUGQW8tDGKZFMuJHAswrfMDAgMTkBo3Kd6Woj"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
#cluster = "testnet"
cluster = "mainnet"
wallet = "/home/alphaprime8/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
